name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTRmMzdmMGUtMGU3ZC00NWI0LWE0NGUtZTFmOWFiNWRhNTJlIiwidGVuYW50X2lkIjoiNjMzYmI3YmYyOWYwZTQ5OGUyYWJlOWI3ZGNhMDBkYjU0MjllYzMwYTA2YzZlOTRjOGMzYWYzNjU5NjU5NmQ3ZSIsImludGVybmFsX3NlY3JldCI6IjU3NTZlNmMxLWE3ZTgtNGUyNC1iYzQ3LTIxZjMwNzJlOWRkYyJ9.e3BTclTJ9Y9dQpsjFKBCdJ9M-FRXsRMkbcQAKxc9x38"
JwtPassword="abfffodfeoffbrgibisdbfsfhfwofhfof"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"